# @Author: Samuel Naranjo Rincon
# @Last Modified time: 2024-10-25

data:
  data_path: ../data/{}/{} #../data/{}/{}
  translation: "schfd100_ICAd15" # mesh dim -> nemat dim
  version: normICArawMAT
  model_type: "krakenSiT_patch"
  from_parcellation: 100
  to_icamap: 15
                                                                                                                                                                                                                             
logging:
  folder_to_save_model: "../logs/SiT/" #"/home/naranjorincon/logs/SiT/" #"../logs/SiT/"
  sanity_file_pth: "/ceph/chpc/shared/janine_bijsterbosch_group/naranjorincon_scratch/NeuroTranslate/surf2netmat/batch/kSiTLN.print"
  model_out_root: "/ceph/chpc/shared/janine_bijsterbosch_group/naranjorincon_scratch/NeuroTranslate/surf2netmat/model_out"
  sanity_check_version: "krakenonly"

training:
# testing to see if given a fcn name, it can call it from utils and use it 
#so we can have one script that we can test on instead of one train script per model test
  train_krakenonly: train_krakenonly
  LR: 0.0001 #0.00001 is original
  bs: 32 # batch size, og is 256
  bs_test: 1
  val_epoch: 5
  epochs: 500 #OG is 30
  lamda: 1.5

transformer:
    depth: 12
    heads: 10
    emb_dropout: 0.3
    dropout: 0.3
    krak_mse_weight: 1000 #1000 # recon weight
    krak_latent_weight: 10 #10 #latent weight
    krak_corrEYE_weight: 100 #1000
    skew_weight: 100
    # ico_patch = patches #based on ico sphere patch num 320 is ico-2, our default. +1 because start token added
    # ico_vertex = verteces
    model_details: "d12h10_adam_demeanL2_SkewLoss"


optimisation:
  optimiser: Adam # SGD = stochastic gradent descent; Adam = Adam optimization

Adam:
  weight_decay: 0.001

AdamW:
  weight_decay: 0.
  
SGD:
  weight_decay: 0.
  momentum: 0.9
  nesterov: False
  
# StepLR: 
#   stepsize: 1000
#   decay: 0.5

# CosineDecay:
#   T_max: 5000
#   eta_min: 0.0001

# sub_ico_0:
#     num_patches: 20 
#     num_vertices: 2145 

# sub_ico_1:
#     num_patches: 80 
#     num_vertices: 561 

# sub_ico_2:
#     num_patches: 320
#     num_vertices: 153 