# @Author: Samuel Naranjo Rincon
# @Last Modified time: 2024-02-21 10:56am
resolution:
  ico: 6
  sub_ico: 2

data:
  dataset: ABCD #ABCD, HCPYA, HCPYA_ABCDdr, infomap_prior_ABCDdr
  parcellation_name: schaefer #schaefer, glasser, ICAnetmat
  parcellation_nodes: 300 #100,300,360, 15
  parcellation_type: full #full, partial #correlation mats
  sub_ids_path: /ceph/chpc/shared/janine_bijsterbosch_group/naranjorincon_scratch/NeuroTranslate/surf2netmat/utils/dr_scripts/neurotranslate_abcd_subject_list.txt
  netmats_paths: /ceph/chpc/shared/janine_bijsterbosch_group/naranjorincon_scratch/NeuroTranslate/ABCD_NetMats
  netmats_paths_for_spatial_versions: /ceph/chpc/shared/janine_bijsterbosch_group/naranjorincon_scratch/NeuroTranslate/brain_reps_datasets/ABCD/maps_and_netmats/ICA_netmats/individual_netmats_{}
  patch_indeces_path: /ceph/chpc/shared/janine_bijsterbosch_group/naranjorincon_scratch/NeuroTranslate/surf2netmat/patch_extraction
  hemisphere: 1L #1R
  path_to_data: /ceph/chpc/shared/janine_bijsterbosch_group/naranjorincon_scratch/NeuroTranslate/brain_reps_datasets/ABCD/ICA_maps/ICAd15_ico06/
  path_to_subject_lists: /ceph/chpc/shared/janine_bijsterbosch_group/naranjorincon_scratch/NeuroTranslate/surf2netmat/utils/subj_ids
  skipped_subject_path: /ceph/chpc/shared/janine_bijsterbosch_group/naranjorincon_scratch/NeuroTranslate/surf2netmat/utils/subj_ids/{}
  output_maps_netmats_path: /ceph/chpc/shared/janine_bijsterbosch_group/naranjorincon_scratch/NeuroTranslate/brain_reps_datasets/ABCD/maps_and_netmats/topo2{}d{}_{}
  output_fornetmats_from_topography: /ceph/chpc/shared/janine_bijsterbosch_group/naranjorincon_scratch/NeuroTranslate/brain_reps_datasets/ABCD/maps_and_netmats/topo2toponetmat_{}
  type_of_netmat: connectome #connectome or topography_maps
  
sub_ico_1:
  num_patches: 80 
  num_vertices: 561 

sub_ico_2:
  num_patches: 320 
  num_vertices: 153

sub_ico_3:
    num_patches: 1280
    num_vertices: 45

sub_ico_4:
    num_patches: 5120
    num_vertices: 15

sub_ico_5:
    num_patches: 20480
    num_vertices: 6 

sub_ico_6:
  num_patches: 81920
  num_vertices:  40962

